#!/usr/bin/env python3
"""Export the frozen Checker-v3 / SEIG specification to plain-JSON artefacts.

This script materialises, straight from `seig.py` (the executable source of truth),
the two artefacts that a reviewer usually asks to inspect without reading code:

  * configs/lexicons.json          -- the reviewer-grade checker lexicons
                                      (forbidden / safety / boundary / calibration regexes)
  * configs/prompt_templates.json  -- the deterministic SEIG evidence prompt (Table 5)

`configs/checker_rulebook_v3.json` (rule priority / negation policy / rewrite
templates) is produced by `SEIG.checker_rulebook()` and is kept alongside these.

Run from the repository root:

    python tools/export_checker_spec.py
"""
from __future__ import annotations

import ast
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SEIG_SRC = os.path.join(ROOT, "seig.py")
OUT_DIR = os.path.join(ROOT, "configs")

# human-readable role of each lexicon constant (documentation only)
ROLES = {
    "_diagnosis_terms": "forbidden: diagnostic / pathology vocabulary",
    "_procedure_terms": "forbidden: treatment / procedure / follow-up vocabulary",
    "_recommendation_cues": "forbidden: recommendation / directive cues",
    "_anatomy_terms": "forbidden: fine-grained colorectal anatomical subsites",
    "_safe_epistemic_disclaimer": "exempt: safe epistemic disclaimers (not a diagnostic claim)",
    "_safe_treatment_disclaimer": "exempt: safe treatment-decision disclaimers",
    "_safe_clinical_action_disclaimer": "exempt: safe clinical-action disclaimers",
    "_safe_anatomy_disclaimer": "exempt: safe anatomy-uncertainty disclaimers",
    "_boundary_terms": "boundary vocabulary",
    "_boundary_descriptor": "boundary shape descriptors",
    "_caution_terms": "hedging / cautious wording lexicon",
    "_strong_certainty": "strong-certainty wording lexicon",
    "_negated_certainty": "negated-certainty exceptions",
    "_deterministic_copula": "deterministic copula / verb forms",
}


def main() -> None:
    src = open(SEIG_SRC, encoding="utf-8").read()
    tree = ast.parse(src)

    lexicons = {}
    prompt = {}
    owner_class = None

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        for stmt in node.body:
            if isinstance(stmt, ast.Assign) and isinstance(stmt.value, ast.Call):
                fn = stmt.value.func
                if isinstance(fn, ast.Attribute) and fn.attr == "compile":
                    name = stmt.targets[0].id
                    if isinstance(stmt.value.args[0], ast.Constant):
                        seg = ast.get_source_segment(src, stmt.value) or ""
                        lexicons[name.lower()] = {
                            "role": ROLES.get(name.lower(), ""),
                            "pattern": stmt.value.args[0].value,
                            "flags": "re.IGNORECASE" if "IGNORECASE" in seg else "",
                        }
            if isinstance(stmt, ast.FunctionDef) and stmt.name == "render_prompt":
                owner_class = node.name
                for sub in ast.walk(stmt):
                    if isinstance(sub, ast.Return) and sub.value is not None:
                        prompt["seig_evidence_prompt_template"] = ast.get_source_segment(src, sub.value)

    lex_out = {
        "_source": "seig.py (class %s) -- reviewer-grade checker lexicons" % (owner_class or "SEIG"),
        "_note": "Executable source of truth is seig.py; this file is generated by tools/export_checker_spec.py.",
        "lexicons": lexicons,
    }
    prompt_out = {
        "_source": "seig.py (class %s, method render_prompt) -- deterministic structured evidence prompt (Table 5)" % (owner_class or "SEIG"),
        "_note": "Executable source of truth is seig.py; this file is generated by tools/export_checker_spec.py.",
        "templates": prompt,
    }

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "lexicons.json"), "w", encoding="utf-8") as f:
        json.dump(lex_out, f, ensure_ascii=False, indent=2)
        f.write("\n")
    with open(os.path.join(OUT_DIR, "prompt_templates.json"), "w", encoding="utf-8") as f:
        json.dump(prompt_out, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print("wrote configs/lexicons.json         (%d lexicons)" % len(lexicons))
    print("wrote configs/prompt_templates.json (%d template(s))" % len(prompt))


if __name__ == "__main__":
    main()
